// manage_web/pages/search.vue
<template>
  <div>
    仅支持 0.21.0 以上版本
  </div>
</template>

<script lang="ts">
import Vue, {PropType} from 'vue'
import {Pagination} from "@pagenote/shared/lib/@types/database";
import {WebPage} from "@pagenote/shared/lib/@types/Types";
import bridgeApi from "../service/requestExt";

type PropA = {}

export default Vue.extend({
  name: 'Search',
  props: {
    propA: {
      type: Object as PropType<PropA>
    }
  },
  data() {
    const defaultData: {
      pagination: Pagination,
      pages: WebPage[],
    } = {
      pagination: {
        total: 0,
        limit: 0,
        pages: 0
      },
      pages:[]
    }
    return {
      ...defaultData,
      keywords: 'pagenote',
      currentPage: 0,
    }
  },
  methods: {
    searchByKeyword() {
      const keywords = this.keywords;
      const query = {
        deleted: false,
        $or:[
          {
            text:{
              $like: keywords
            }
          },
          {
            domain:{
              $like: keywords
            }
          },
          {
            tip:{
              $like: keywords
            }
          },
          {
            context:{
              $like: keywords
            }
          },
          {
            categories:{
              $like: keywords
            }
          },
        ]
      }
      const pagination = this.pagination;
      bridgeApi.lightpage.getLightPages({
        limit: pagination.limit,
        skip: this.currentPage * pagination.limit,
        query: query
      }).then( (result)=> {
        console.log('拉取结果',result)
        if(result.success){
          this.pages = result.data.pages
          this.pagination = result.data.pagination
        }
      });
    },
  },
  computed: {},
  mounted() {
    this.searchByKeyword()
  },
})
</script>

<style lang="scss">

</style>

// web/pages/search.tsx
import React, {useEffect, useState} from 'react';
import api from '../api/index'
import {WebPage} from "@pagenote/shared/lib/@types/Types";
import {Pagination} from "@pagenote/shared/lib/@types/database";
import { useRouter } from 'next/router'

export default function Search() {
    const router = useRouter()
    const { keywords='pagenote' } = router.query
    const [pages,setPages] = useState<WebPage[]>([]);
    const [pagination,setPagination] = useState<Pagination>(function () {
        return{
            pages: 0,
            limit: 10,
            total: 0
        }
    })
    const [currentPage,setCurrentPage] = useState(0);

    function searchPages() {
        const query = {
            deleted: false,
            $or:[
                {
                    text:{
                        $like: keywords
                    }
                },
                {
                    domain:{
                        $like: keywords
                    }
                },
                {
                    tip:{
                        $like: keywords
                    }
                },
                {
                    context:{
                        $like: keywords
                    }
                },
                {
                    categories:{
                        $like: keywords
                    }
                },
            ]
        }
        console.time('sousuo')
        api.lightpage.getLightPages({
            limit: pagination.limit,
            skip: currentPage * pagination.limit,
            query: query
        }).then(function (result) {
            console.log('拉取结果',result)
            console.timeEnd('sousuo')
            if(result.success){
                setPages(result.data.pages)
                setPagination(result.data.pagination)
            }
        })
    }

    useEffect(function () {
        searchPages()
    },[currentPage,keywords])

    useEffect(function () {

        api.setting.getUserSetting().then(function (result) {
            // console.log('user setting ',result)
        })

        api.commonAction.usage().then(function (result) {
            console.log(result)
        })

        api.browserAction.getBrowserActionInfo({
            tabId: undefined
        }).then(function (result) {
            // console.log(result)
        })

        setTimeout(function () {
            api.browserAction.setBrowserActionDisplay({
                info: {
                    text: 'hi',
                    color: '#9affe9',
                    title: '和来来来',
                },
                tabId: undefined
            }).then(function (result) {
                // console.log('修改颜色',result)
            })
        },1000)

    },[])

    return(
        <div className={'container w-1/2 sm:w-full m-auto my-8'}>
            {
                pages.map((page,index)=>(
                    <div className={'text-base'} key={page.key}>
                        {index}: {page.plainData.title || page.plainData.url}
                    </div>
                ))
            }
            <div>
                搜索结果共有：{pagination.total} 个
                {
                    new Array(pagination.pages).fill(1).map(function (i,index) {
                        return <button key={index} onClick={()=>{setCurrentPage(index)}}>{index}</button>
                    })
                }
            </div>
        </div>
    )
}
